version: '3.1'

services: 
  blackbox-exporter:
      image: prom/blackbox-exporter
      container_name: blackbox_exporter_1
      ports: 
        - 9100:9100
        - 9115:9115
      restart: always       

  nginx:
      image: nginx
      container_name: nginx_1
      ports: 
        - 80:80
      restart: always

